//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedProgramming_Lesson2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdvancedProgramming_Lesson2.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum of 5 copies can be borrowed.
        /// </summary>
        public static string AMaximumOf5CopiesCanBeBorrowed {
            get {
                return ResourceManager.GetString("AMaximumOf5CopiesCanBeBorrowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Are_you_sure_ {
            get {
                return ResourceManager.GetString("Are you sure?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string Back_to_list {
            get {
                return ResourceManager.GetString("Back to list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client number.
        /// </summary>
        public static string ClientNumber {
            get {
                return ResourceManager.GetString("ClientNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conseratory.
        /// </summary>
        public static string Conseratory {
            get {
                return ResourceManager.GetString("Conseratory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        public static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of borrow.
        /// </summary>
        public static string DateOfBorrow {
            get {
                return ResourceManager.GetString("DateOfBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of return.
        /// </summary>
        public static string DateOfReturn {
            get {
                return ResourceManager.GetString("DateOfReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete record.
        /// </summary>
        public static string Delete_record {
            get {
                return ResourceManager.GetString("Delete record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of copies (maximum 5).
        /// </summary>
        public static string EnterTheNumberOfCopiesMaximum5 {
            get {
                return ResourceManager.GetString("EnterTheNumberOfCopiesMaximum5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise.
        /// </summary>
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab.
        /// </summary>
        public static string Lab {
            get {
                return ResourceManager.GetString("Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about creation of mvc .net core apps.
        /// </summary>
        public static string Learn_End {
            get {
                return ResourceManager.GetString("Learn End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        public static string Learn_Start {
            get {
                return ResourceManager.GetString("Learn Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string Lecture {
            get {
                return ResourceManager.GetString("Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        public static string Lecturer {
            get {
                return ResourceManager.GetString("Lecturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose.
        /// </summary>
        public static string Please_choose {
            get {
                return ResourceManager.GetString("Please choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a customer number.
        /// </summary>
        public static string PleaseEnterACustomerNumber {
            get {
                return ResourceManager.GetString("PleaseEnterACustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date.
        /// </summary>
        public static string PleaseEnterADate {
            get {
                return ResourceManager.GetString("PleaseEnterADate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first and last name.
        /// </summary>
        public static string PleaseEnterFirstAndLastName {
            get {
                return ResourceManager.GetString("PleaseEnterFirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the author.
        /// </summary>
        public static string PleaseEnterTheAuthor {
            get {
                return ResourceManager.GetString("PleaseEnterTheAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the borrow date.
        /// </summary>
        public static string PleaseEnterTheBorrowDate {
            get {
                return ResourceManager.GetString("PleaseEnterTheBorrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the subject.
        /// </summary>
        public static string PleaseEnterTheNameOfTheSubject {
            get {
                return ResourceManager.GetString("PleaseEnterTheNameOfTheSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the return date.
        /// </summary>
        public static string PleaseEnterTheReturnDate {
            get {
                return ResourceManager.GetString("PleaseEnterTheReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Email Address.
        /// </summary>
        public static string PleaseInsertEmailAddress {
            get {
                return ResourceManager.GetString("PleaseInsertEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert Phone Number.
        /// </summary>
        public static string PleaseInsertPhoneNumber {
            get {
                return ResourceManager.GetString("PleaseInsertPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert title.
        /// </summary>
        public static string PleaseInsertTitle {
            get {
                return ResourceManager.GetString("PleaseInsertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the type of subject.
        /// </summary>
        public static string PleaseSelectTheTypeOfSubject {
            get {
                return ResourceManager.GetString("PleaseSelectTheTypeOfSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a secret.
        /// </summary>
        public static string Privacy_Policy_Content {
            get {
                return ResourceManager.GetString("Privacy Policy Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record details.
        /// </summary>
        public static string Record_details {
            get {
                return ResourceManager.GetString("Record details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record editing.
        /// </summary>
        public static string Record_Editing {
            get {
                return ResourceManager.GetString("Record Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer number should consist of 5 digits.
        /// </summary>
        public static string TheCustomerNumberShouldConsistOf5Digits {
            get {
                return ResourceManager.GetString("TheCustomerNumberShouldConsistOf5Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of subject.
        /// </summary>
        public static string TypeOfSubject {
            get {
                return ResourceManager.GetString("TypeOfSubject", resourceCulture);
            }
        }
    }
}
